### ISSUE TITLE
Why didn't use the DMA2D?

### ISSUE THREAD

**Issue by lizhen9880** [littlevgl/lv_port_stm32f429_disco_sw4stm32#6]
Why didn't use the DMA2D?
The DMA2D init function has been defined here [HAL_DMA2D_MspInit](https://github.com/lvgl/lv_port_stm32f429_disco/blob/master/hal_stm_lvgl/tft/tft.c#L420) but never used. 
And using DMA2  Stream0 to transfer data in [tft_flush](https://github.com/lvgl/lv_port_stm32f429_disco/blob/master/hal_stm_lvgl/tft/tft.c#L183)，but why?

**Comment by kisvegabor** [comment]
LVGL has built in support for DMA2D, see [here](https://github.com/lvgl/lvgl/blob/master/src/gpu/lv_gpu_stm32_dma2d.c).

**Comment by lizhen9880** [comment]
> LVGL has built in support for DMA2D, see [here](https://github.com/lvgl/lvgl/blob/master/src/gpu/lv_gpu_stm32_dma2d.c).

wow！excellent！
